/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    java
    id("org.springframework.boot") version "3.5.7"
    id("io.spring.dependency-management") version "1.1.6"
    jacoco
}

group = "com.example"
version = "0.1.1"
description = "Spring Project for managing eshop transactions"

java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

repositories {
    mavenCentral()
}

val logbackVersion = "1.5.25"
val lombokVersion = "1.18.30"

dependencies {

    /* Spring Boot */
    implementation("org.springframework.boot:spring-boot-starter-actuator")
    implementation("org.springframework.boot:spring-boot-starter-web")
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")

    /* Databases */
    runtimeOnly("com.h2database:h2")
    runtimeOnly("org.postgresql:postgresql")

    /* Lombok */
    compileOnly("org.projectlombok:lombok:$lombokVersion")
    annotationProcessor("org.projectlombok:lombok:$lombokVersion")

    /* OpenAPI */
    implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.5")

    /* Liquibase */
    implementation("org.liquibase:liquibase-core:5.0.0")

    /* JSON */
    implementation("com.fasterxml.jackson.core:jackson-databind:2.20.0")

    /* Logging */
    implementation("ch.qos.logback:logback-classic:$logbackVersion")
    implementation("ch.qos.logback:logback-core:$logbackVersion")
    implementation("net.logstash.logback:logstash-logback-encoder:8.1")

    /* Tests */
    testImplementation("org.springframework.boot:spring-boot-starter-test")
    testImplementation("org.mockito:mockito-core")
    testImplementation("org.mockito:mockito-junit-jupiter")
}

tasks.test {
    useJUnitPlatform()
}

tasks.bootJar {
    archiveFileName.set("eshop-manager.jar")
}

jacoco {
    toolVersion = "0.8.12"
}

tasks.jacocoTestReport {
    dependsOn(tasks.test)

    reports {
        html.required.set(true)
        xml.required.set(true)
        csv.required.set(false)
    }

    classDirectories.setFrom(
        files(classDirectories.files.map {
            fileTree(it) {
                exclude(
                    "**/com/example/eshop/config/**",
                    "**/com/example/eshop/aop/**",
                    "**/com/example/eshop/enums/**",
                    "**/com/example/eshop/dao/**",
                    "**/com/example/eshop/utils/**",
                    "**/com/example/eshop/exception/**"
                )
            }
        })
    )
}